import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import SearchBar from '../src/components/SearchBar/SearchBar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 flex justify-center items-center">
        <SearchBar />
      </main>
    </>
  );
};

export default Home;
